# Generated by Django 6.0.1 on 2026-02-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Dronataire", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
